/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import java.awt.Font;
import java.awt.Color;
import javax.swing.JRadioButton;
import javax.swing.LayoutStyle.ComponentPlacement;

import dtos.FireAlarmSensor;
import interfaces.IFireAlarmService;
import response.models.FireAlarmSensorSingleResponse;
import rmi.client.Client;


import java.awt.event.ActionListener;
import java.rmi.RemoteException;
import java.util.List;
import java.awt.event.ActionEvent;

/**
 *
 * @author Supun Randima
 */
public class newSensorUI extends javax.swing.JFrame {

    /**
     * Creates new form newSensorUI
     */
	 private IFireAlarmService stub = null;
	 private Client client = new Client();
	 private FireAlarmSensor fireAlarmSensor = new FireAlarmSensor();
		
    public newSensorUI() {
        this.stub = client.getStub();
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRoomNo = new javax.swing.JTextField();
        txtRoomNo.setToolTipText("Enter room no");
        txtFloorNo = new javax.swing.JTextField();
        txtFloorNo.setToolTipText("Enter floor no");
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        rdbtnInactive = new JRadioButton("Inactive");
        rdbtnInactive.setFont(new Font("Tahoma", Font.PLAIN, 14));
        rdbtnInactive.setToolTipText("Sensor is in inactive status");
        rdbtnInactive.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		if(rdbtnInactive.isSelected()) {
        			rdbtnActive.setSelected(false);
        		}
        	}
        });
        rdbtnActive = new JRadioButton("Active");
        rdbtnActive.setFont(new Font("Tahoma", Font.PLAIN, 14));
        rdbtnActive.setToolTipText("Sensor is in active status");
        rdbtnActive.setSelected(true);
        
        jButton2.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		String floorNo = txtFloorNo.getText().toString();
        		String roomNo = txtRoomNo.getText().toString();
        		boolean status;
        		if(rdbtnActive.isSelected()) {
        			status = true;
        		}else {
        			status = false;
        		}
        		
        		 if(!isEmpty("Floor No", floorNo.trim())){ }
        		
        		 if(!isEmpty("Room No", roomNo.trim())) {}
        		 else {
        			 try {
        			 
        				int fNo = Integer.parseInt(floorNo.trim());
                		int rNo = Integer.parseInt(roomNo.trim());
                		 
                		fireAlarmSensor.setFloor_no(fNo);
                		fireAlarmSensor.setRoom_no(rNo);
                		fireAlarmSensor.setStatus(true);
                		
//                		initalized default values in co2 and smoke level
                		fireAlarmSensor.setCo2_level(1);
                		fireAlarmSensor.setSmoke_level(1);
                		
                	    try {
                	    	FireAlarmSensorSingleResponse response = stub.createFireAlarmSensor(fireAlarmSensor);
                	    	JOptionPane.showMessageDialog(null, response.getStatus());
        				} catch (RemoteException ex) {
        					// TODO Auto-generated catch block
        					ex.printStackTrace();
        				} 
        			 }catch (Exception exc) {
        				 System.out.println(exc);
        			 }
        		 }
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(948, 602));

        jLabel10.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Register Fire Alarm");

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Floor Number");

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Room Number");

        txtRoomNo.setBackground(new java.awt.Color(204, 204, 204));
        txtRoomNo.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N

        txtFloorNo.setBackground(new java.awt.Color(204, 204, 204));
        txtFloorNo.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Save");
        
        label = new JLabel();
        label.setText("Status");
        label.setForeground(Color.WHITE);
        label.setFont(new Font("Sylfaen", Font.PLAIN, 18));
        
       
        rdbtnActive.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		if(rdbtnActive.isSelected()) {
        			rdbtnInactive.setSelected(false);
        		}
        	}
        });
        rdbtnActive.setBackground(Color.LIGHT_GRAY);
        
        
        rdbtnInactive.setBackground(Color.LIGHT_GRAY);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap(65, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel2)
        								.addComponent(jLabel1)
        								.addComponent(label, GroupLayout.PREFERRED_SIZE, 109, GroupLayout.PREFERRED_SIZE))
        							.addGap(44))
        						.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        							.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 113, GroupLayout.PREFERRED_SIZE)
        							.addGap(5)))
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        							.addComponent(txtFloorNo, GroupLayout.PREFERRED_SIZE, 228, GroupLayout.PREFERRED_SIZE)
        							.addComponent(txtRoomNo, GroupLayout.PREFERRED_SIZE, 228, GroupLayout.PREFERRED_SIZE)
        							.addGroup(jPanel1Layout.createSequentialGroup()
        								.addComponent(rdbtnActive, GroupLayout.PREFERRED_SIZE, 77, GroupLayout.PREFERRED_SIZE)
        								.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(rdbtnInactive, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
        								.addGap(34)))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGap(54)
        							.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 113, GroupLayout.PREFERRED_SIZE)))
        					.addContainerGap(48, Short.MAX_VALUE))
        				.addGroup(Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        					.addComponent(jLabel10)
        					.addGap(149))))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(26)
        			.addComponent(jLabel10)
        			.addGap(38)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(txtFloorNo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(32)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(txtRoomNo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(27)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(label, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(rdbtnActive)
        				.addComponent(rdbtnInactive))
        			.addGap(59)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE))
        			.addGap(70))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    	 this.dispose();
         new mainUI().setVisible(true); 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newSensorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newSensorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newSensorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newSensorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newSensorUI().setVisible(true);
            }
        });
    }
    
    public boolean isEmpty(String name, String value){
        if(value.trim().equals("")){
            JOptionPane.showMessageDialog(null, name + " Required");
            return false; 
        }
        else return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtRoomNo;
    private javax.swing.JTextField txtFloorNo;
    private JLabel label;
    private JRadioButton rdbtnActive;
    private JRadioButton rdbtnInactive;
    // End of variables declaration//GEN-END:variables
}
